# 異質資料的運用
### 本範例示範了一個標準的量化投資資料集會有的樣貌

In [3]:
# 首先讀取檔案，你會發現公司代碼應該是文字格式，卻被pandas誤處理成整數欄位，可能造成問題
import pandas
data = pandas.read_csv('listed_data.csv')
print(data.info())
#將coid轉換成文字格式
data['coid'] = data['coid'].astype(str)
data.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414986 entries, 0 to 414985
Data columns (total 8 columns):
報酬率-Ln      414986 non-null float64
coid        414986 non-null int64
mdate       414986 non-null object
常續性稅後淨利     414986 non-null float64
zdate       414986 non-null object
單月營收(千元)    414953 non-null float64
收盤價(元)      414986 non-null float64
外資總投資股數     414986 non-null float64
dtypes: float64(5), int64(1), object(2)
memory usage: 25.3+ MB
None

   報酬率-Ln  coid       mdate  常續性稅後淨利       zdate  單月營收(千元)  收盤價(元)  外資總投資股數
0 -2.6286  9958  2018-03-01      0.0  2018-04-16  117283.0    82.6   5246.0
1  0.4831  9958  2018-03-01      0.0  2018-04-17  117283.0    83.0   5487.0
2  0.1204  9958  2018-03-01      0.0  2018-04-18  117283.0    83.1   5364.0
3  0.4802  9958  2018-03-01      0.0  2018-04-19  117283.0    83.5   5484.0
4 -1.0837  9958  2018-03-01      0.0  2018-04-20  117283.0    82.6   5527.0

In [4]:
# 再檢查一次資料格式，確實轉換為object
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414986 entries, 0 to 414985
Data columns (total 8 columns):
報酬率-Ln      414986 non-null float64
coid        414986 non-null object
mdate       414986 non-null object
常續性稅後淨利     414986 non-null float64
zdate       414986 non-null object
單月營收(千元)    414953 non-null float64
收盤價(元)      414986 non-null float64
外資總投資股數     414986 non-null float64
dtypes: float64(5), object(3)
memory usage: 25.3+ MB

### 試著用dill來儲存資料，而不要存成csv

In [5]:
import dill
dill.dump(data, open('dictionary.dill','wb'))

上一步執行完畢後，試著用jupyter notebook的kernal -> restar來清除記憶體，然後執行下一步

In [2]:
import dill
data = dill.load(open('dictionary.dill','rb'))
data.info()
# 試著看看底下coid的欄位，是否保持在object而非int

<class 'pandas.core.frame.DataFrame'>
Int64Index: 262027 entries, 0 to 262026
Data columns (total 10 columns):
報酬率-Ln       262027 non-null float64
coid         262027 non-null object
mdate        262027 non-null object
常續性稅後淨利      262027 non-null float64
zdate        262027 non-null datetime64[ns]
單月營收(千元)     262027 non-null float64
收盤價(元)       262027 non-null float64
外資總投資股數      262027 non-null float64
報酬率-Ln-20    262008 non-null float64
上個月報酬率       12856 non-null float64
dtypes: datetime64[ns](1), float64(7), object(2)
memory usage: 22.0+ MB

#### 接著快速看過資料的樣貌，最合適的方式就是看台積電(2330)
#### 因為台積電這樣重要的公司，必然有各種資料
#### 本範例包含：
#### 常續性稅後淨利：一年四次，不定日期
#### 單月營收：一年12次，不定日期
#### 收盤價(元)/外資總投資股數/報酬率-Ln：每個交易日公布

In [8]:
# 去除太舊的資料，只看2019開始的
data = data[data['zdate']>'2018-12-31'].reset_index(drop=True)
data[data['coid']=='2330']

,報酬率-Ln,coid,mdate,常續性稅後淨利,zdate,單月營收(千元),收盤價(元),外資總投資股數,報酬率-Ln-20
183431,-2.6968,2330,2018-09-01,90012762.0,2019-01-02,98389414.0,219.5,20018233.0,-6.3969
183432,-1.8391,2330,2018-09-01,90012762.0,2019-01-03,98389414.0,215.5,19998889.0,-4.7574
183433,-3.5423,2330,2018-09-01,90012762.0,2019-01-04,98389414.0,208.0,19972833.0,-5.6090
183434,2.3754,2330,2018-09-01,90012762.0,2019-01-07,98389414.0,213.0,19976458.0,-3.6871
183435,-0.9434,2330,2018-09-01,90012762.0,2019-01-08,98389414.0,211.0,19977204.0,-3.7214
...,...,...,...,...,...,...,...,...,...
183731,2.6859,2330,2019-12-01,117107626.0,2020-04-07,107884396.0,283.0,19646818.0,-9.7096
183732,0.7042,2330,2019-12-01,117107626.0,2020-04-08,107884396.0,285.0,19657042.0,-5.9431
183733,-0.7042,2330,2019-12-01,117107626.0,2020-04-09,107884396.0,283.0,19662392.0,-7.1371
183734,-1.2445,2330,2019-12-01,117107626.0,2020-04-10,107884396.0,279.5,19658600.0,-6.7395
183735,-0.3584,2330,2019-12-01,117107626.0,2020-04-13,107884396.0,279.5,19658600.0,-4.4132

接著直接使用pandas的rolling計算移動平均/加總  
pandas的rolling()基本上就足以製造出各種技術指標  
我們會在後面第二示範

In [9]:
# 計算20天移動報酬率
data['報酬率-Ln-20'] = data['報酬率-Ln'].rolling(window=20).sum()
data[data['coid']=='2330']

,報酬率-Ln,coid,mdate,常續性稅後淨利,zdate,單月營收(千元),收盤價(元),外資總投資股數,報酬率-Ln-20
183431,-2.6968,2330,2018-09-01,90012762.0,2019-01-02,98389414.0,219.5,20018233.0,-6.6825
183432,-1.8391,2330,2018-09-01,90012762.0,2019-01-03,98389414.0,215.5,19998889.0,-0.9564
183433,-3.5423,2330,2018-09-01,90012762.0,2019-01-04,98389414.0,208.0,19972833.0,-2.3109
183434,2.3754,2330,2018-09-01,90012762.0,2019-01-07,98389414.0,213.0,19976458.0,3.4988
183435,-0.9434,2330,2018-09-01,90012762.0,2019-01-08,98389414.0,211.0,19977204.0,13.0915
...,...,...,...,...,...,...,...,...,...
183731,2.6859,2330,2019-12-01,117107626.0,2020-04-07,107884396.0,283.0,19646818.0,-9.7096
183732,0.7042,2330,2019-12-01,117107626.0,2020-04-08,107884396.0,285.0,19657042.0,-5.9431
183733,-0.7042,2330,2019-12-01,117107626.0,2020-04-09,107884396.0,283.0,19662392.0,-7.1371
183734,-1.2445,2330,2019-12-01,117107626.0,2020-04-10,107884396.0,279.5,19658600.0,-6.7395
183735,-0.3584,2330,2019-12-01,117107626.0,2020-04-13,107884396.0,279.5,19658600.0,-4.4132

### 計算"上個月的報酬率"
但是滾動加總20天(約等於一個月的交易日數量)的報酬率，跟真正的一個月報酬率意義不同  
我們另外試著計算每個月的報酬率，因此一年只會剩下12筆資料

In [10]:
# 每月初計算上個月報酬率
import numpy
data = data[data['zdate']>'2018-12-31'].reset_index(drop=True)
data['zdate'] = data['zdate'].astype('datetime64')
last_month = 1
last_date = numpy.datetime64('2019-01-02')
outcome = None
for this_date in data['zdate'].unique():
    this_month = this_date.astype('datetime64[M]').astype(int)%12+1
    if this_month != last_month:
        print(this_date)
        this_coid = data.loc[data['zdate']==this_date,'coid'].values
        ans = numpy.log(data.loc[data['zdate']==this_date,['收盤價(元)']].reset_index(drop=True)/data.loc[data['zdate']==last_date,['收盤價(元)']].reset_index(drop=True))
        ans = ans.rename(columns={'收盤價(元)':'上個月報酬率'})
        ans['zdate'] = this_date
        ans['coid'] = this_coid
        if outcome is None:
            outcome = ans
        else:
            outcome = outcome.append(ans,sort=False)
        last_month = this_month
        last_date = this_date
data = data.merge(outcome,on=['zdate','coid'],how='left')

2019-02-11T00:00:00.000000000
2019-03-04T00:00:00.000000000
2019-04-01T00:00:00.000000000
2019-05-02T00:00:00.000000000
2019-06-03T00:00:00.000000000
2019-07-01T00:00:00.000000000
2019-08-01T00:00:00.000000000
2019-09-02T00:00:00.000000000
2019-10-01T00:00:00.000000000
2019-11-01T00:00:00.000000000
2019-12-02T00:00:00.000000000
2020-01-02T00:00:00.000000000
2020-02-03T00:00:00.000000000
2020-03-02T00:00:00.000000000
2020-04-01T00:00:00.000000000

C:\Users\zyx\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in log
  del sys.path[0]

In [11]:
# 同樣看看台積電的計算結果
data[data['coid']=='2330'].dropna()

,報酬率-Ln,coid,mdate,常續性稅後淨利,zdate,單月營收(千元),收盤價(元),外資總投資股數,報酬率-Ln-20,上個月報酬率
183452,3.1183,2330,2018-09-01,90012762.0,2019-02-11,98389414.0,228.0,20017061.0,5.6384,2.469241
183465,-1.4753,2330,2018-12-01,100588107.0,2019-03-04,98389414.0,235.5,20102138.0,5.4540,0.032365
183485,0.0000,2330,2018-12-01,100588107.0,2019-04-01,74693615.0,245.5,20166992.0,4.1586,-0.353207
183505,0.0000,2330,2018-12-01,100588107.0,2019-05-02,74693615.0,259.0,20317870.0,5.3530,2.647198
183527,1.0560,2330,2019-03-01,61925133.0,2019-06-03,74693615.0,238.0,20126972.0,-8.4558,2.562641
183546,3.8979,2330,2019-03-01,61925133.0,2019-07-01,84757724.0,248.5,20009942.0,8.6387,0.043172
183569,-1.1628,2330,2019-03-01,61925133.0,2019-08-01,106117619.0,256.5,20051532.0,4.9962,0.031686
183590,-0.5808,2330,2019-06-01,66408272.0,2019-09-02,106117619.0,257.5,20017043.0,2.3577,0.003891
183609,2.8988,2330,2019-06-01,66408272.0,2019-10-01,106039531.0,280.0,20250660.0,8.5480,2.467207
183630,0.1674,2330,2019-06-01,66408272.0,2019-11-01,107884396.0,299.0,20370029.0,6.7442,2.846851
183651,0.8163,2330,2019-09-01,101717149.0,2019-12-02,107884396.0,307.5,20350660.0,1.9180,2.943464
183673,2.3882,2330,2019-09-01,101717149.0,2020-01-02,107884396.0,339.0,20318688.0,10.7393,0.002954
183688,-1.5748,2330,2019-09-01,101717149.0,2020-02-03,107884396.0,315.0,20203980.0,-5.5570,-0.073427
183707,-1.5949,2330,2019-12-01,117107626.0,2020-03-02,107884396.0,311.0,19995226.0,-2.8525,-0.012780
183729,-0.9166,2330,2019-12-01,117107626.0,2020-04-01,107884396.0,271.5,19621338.0,-15.5890,-0.135831

# 進行一個簡單的機器學習
#### 看看xgboost有沒有辦法找出那四個變數與兩種累計報酬率的關係
#### 只要你把target_field = '報酬率-Ln-20' 或是
#### target_field = '上個月報酬率'  這兩個選擇一個mark掉，就會跑另一個的機器學習

In [15]:
# 固定窗口
target_field = '上個月報酬率'
#target_field = '報酬率-Ln-20'
x_filed = ['常續性稅後淨利','單月營收(千元)','收盤價(元)','外資總投資股數']
fix_data = data[['coid','zdate',target_field]].replace([numpy.inf, -numpy.inf], numpy.nan).dropna()

fix_data_sample = None
for this_date in fix_data['zdate'].unique():
    this_data = fix_data[fix_data['zdate']==this_date]
    this_data = this_data.sort_values(by=[target_field])
    this_data = this_data.reset_index(drop=True).reset_index()
    
    this_data['分位數'] = (len(this_data) - this_data['index'])/len(this_data)

    this_data = this_data.drop(columns=['index'])
    
    if fix_data_sample is None:
        fix_data_sample = this_data
    else:
        fix_data_sample = fix_data_sample.append(this_data,sort=False)
    
fix_data_sample['排名分組'] = 0
#fix_data_sample.loc[fix_data_sample['分位數']<=0.75,'排名分組'] = 3
#fix_data_sample.loc[fix_data_sample['分位數']<=0.50,'排名分組'] = 2
fix_data_sample.loc[fix_data_sample['分位數']<=0.25,'排名分組'] = 1
fix_data_sample = fix_data_sample.merge(data[['coid','zdate']+x_filed],on=['zdate','coid'],how='left')
fix_data_sample

,coid,zdate,上個月報酬率,分位數,排名分組,常續性稅後淨利,單月營收(千元),收盤價(元),外資總投資股數
0,3011,2019-02-11,-6.017956,1.000000,0,-501.0,142226.0,7.45,518.0
1,3536,2019-02-11,-3.258781,0.998821,0,-12877.0,74728.0,7.86,352.0
2,2399,2019-02-11,-3.102674,0.997642,0,-21702.0,193435.0,9.48,26331.0
3,2380,2019-02-11,-2.894536,0.996462,0,-93251.0,208247.0,4.26,17938.0
4,2332,2019-02-11,-2.885826,0.995283,0,37526.0,1606801.0,12.25,92968.0
...,...,...,...,...,...,...,...,...,...
12826,2910,2020-04-01,0.128359,0.005787,1,16220.0,35885.0,30.30,243.0
12827,4119,2020-04-01,0.140308,0.004630,1,88901.0,193285.0,137.50,12649.0
12828,6166,2020-04-01,0.204068,0.003472,1,217113.0,769747.0,68.80,41062.0
12829,2368,2020-04-01,0.484018,0.002315,1,381397.0,1838886.0,25.15,60569.0
12830,4572,2020-04-01,0.850986,0.001157,1,35010.0,55368.0,81.50,88.0

In [16]:
import xgboost
xgb_train = xgboost.DMatrix(fix_data_sample[x_filed].values, label=fix_data_sample['排名分組'].values)
xgb_params = {
        'objective': 'binary:logistic',
        'eval_metric': 'logloss',
    }
bst = xgboost.train(xgb_params,
                    xgb_train,
                    num_boost_round=100,
                    )

In [17]:
# 比較準確度，為什麼樣本較大，反而比較不準？
fix_data_sample['分類機率'] = bst.predict(xgb_train)
fix_data_sample['預測分組'] = 0
fix_data_sample.loc[fix_data_sample['分類機率']>0.5,'預測分組']  = 1
fix_data_sample['預測分組差異'] = fix_data_sample['排名分組'] - fix_data_sample['預測分組']
#印出猜中的比重
len(fix_data_sample[fix_data_sample['預測分組差異']==0])/len(fix_data_sample)

0.8361780063907723

使用'上個月報酬率'的命中率是0.8361
比使用20天滾動報酬率的0.7939還高
似乎更大的資料集，不一定有更好的結果！